test: ParallelBresenham.cpp ../FHDRaster/FHDRaster.cpp ../BresenhamAlgorithm/BresenhamAlgorithm.cpp
	g++ test.cpp -o test ParallelBresenham.cpp ../FHDRaster/FHDRaster.cpp ../BresenhamAlgorithm/BresenhamAlgorithm.cpp -lpthread
